// SPDX-FileCopyrightText: 2024 Alexandru Fikl <alexfikl@gmail.com>
// SPDX-License-Identifier: MIT

// NOTE: This file was generated by `generate-coefficients-eval.py` and
// should not be modified.

use num::complex::{c64, Complex64};

use crate::netbrot::Matrix;

#[allow(dead_code)]
pub fn coeffs_2x2_1(mat: &Matrix, c: Complex64) -> [[([u32; 2], Complex64); 5]; 2] {
    let a_0_0 = mat[(0, 0)];
    let a_0_1 = mat[(0, 1)];
    let a_1_0 = mat[(1, 0)];
    let a_1_1 = mat[(1, 1)];

    [
        [
            ([2, 0], 1.000000e+00 * a_0_0.powi(2)),
            ([1, 1], 2.000000e+00 * a_0_0 * a_0_1),
            ([1, 0], c64(-1.0, 0.0)),
            ([0, 2], 1.000000e+00 * a_0_1.powi(2)),
            ([0, 0], 1.000000e+00 * c),
        ],
        [
            ([2, 0], 1.000000e+00 * a_1_0.powi(2)),
            ([1, 1], 2.000000e+00 * a_1_0 * a_1_1),
            ([0, 2], 1.000000e+00 * a_1_1.powi(2)),
            ([0, 1], c64(-1.0, 0.0)),
            ([0, 0], 1.000000e+00 * c),
        ],
    ]
}
